[package]
name = "pokecord"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jpeg-encoder = "0.5.1"
png = "0.17.5"
rustboyadvance-core = { path = "./rustboyadvance-ng/core" }
